- name: Install and configure nginx
  #hosts: web
  hosts: all
  become: yes
  #gather_facts: no
  vars:
  #  nginx_port: 80
    packages:
      - git
      - nginx

  tasks:
    - name: install nginx
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
        #- git
        #- nginx
      loop_control:
        label: "{{ item }}"
      when: ansible_facts.os_family == "RedHat"
    - debug:
        msg: "Nginx installed on port {{ nginx_port }} "
    - name: install nginx on ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts.os_family == "Ubuntu"
    - name: copy nginx file
      copy:
        src: dummy.conf
        dest: /etc/nginx/nginx-dummy.conf
      notify: restart nginx

    - meta: flush_handlers   # forces the handlers to finish at this stage

    - debug:
        msg: "nginx restarted before this line"
    - debug:
        msg: "Details of inventory {{ inventory_hostname }} OS={{ ansible_facts.distribution }} on {{ env }}"
    
    - block:   # try{} block
        - name: gather service facts
          service_facts:

        - name: stop nginx if running
          service:
            name: nginx
            state: stopped
          when:
            - "'nginx.service' in ansible_facts.services"
            - ansible_facts.services['nginx.service'].state == 'running' 
    
      rescue:  # except{} block , when something failed
        - debug:
            msg: "nginx not installed or service failed"
      
      always:   # finally{} block , always runs
        - debug:
            msg: "nginx check completed"
      
    - name:  Create Hello file for jinja2
      template:
        src: hello.j2
        dest: /home/ec2-user/hello.txt
    
    - name: system facts from jinja2
      template:
        src: system.j2
        dest: /home/ec2-user/latest_system_facts.log
    
    - name: pull system facts
      fetch:
        src: /home/ec2-user/latest_system_facts.log
        dest: /output/web_server_facts.log
        flat: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
