- name: Install and configure nginx
  hosts: web
  become: yes
  # gather_facts: no

  tasks:
    - name: install nginx on Amazon Linux
      yum:
        name: nginx
        state: present
      when: ansible_facts.os_family == "RedHat"

    - name: install nginx on ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts.os_family == "Ubuntu"

    - name: copy nginx file
      copy:
        src: dummy.conf
        dest: /etc/nginx/nginx-dummy.conf
      notify: restart nginx

    - meta: flush_handlers   # forces the handlers to finish at this stage

    - debug:
        msg: "nginx restarted before this line"

    - debug:
        msg: "Details of inventory {{ inventory_hostname }} OS={{ ansible_facts.distribution }}"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted