- name: Install and configure nginx
  #hosts: web
  hosts: all
  become: yes
  #gather_facts: no
  vars:
  #  nginx_port: 80
    packages:
      - git
      - nginx

  tasks:
    - name: install nginx
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
        #- git
        #- nginx
      loop_control:
        label: {{ item }}
      when: ansible_facts.os_family == "RedHat"

    - debug:
        msg: "Nginx installed on port {{ nginx_port }} "

    - name: install nginx on ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts.os_family == "Ubuntu"

    - name: copy nginx file
      copy:
        src: dummy.conf
        dest: /etc/nginx/nginx-dummy.conf
      notify: restart nginx

    - meta: flush_handlers   # forces the handlers to finish at this stage

    - debug:
        msg: "nginx restarted before this line"

    - debug:
        msg: "Details of inventory {{ inventory_hostname }} OS={{ ansible_facts.distribution }} on {{ env }}"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
