plugin: amazon.aws.ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Env: dev

keyed_groups:
  - key: tags.Role
    prefix: role
  - key: tags.Env
    prefix: env

hostnames:
  - private-ip-address

compose:
  ansible_host: private-ip-address